name: 'data-constellation-sociale'
services:
  postgres:
    container_name: constellation-sociale-data
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  sidecar:
    container_name: constellation-sociale-loading
    image: ghcr.io/association-constellation-sociale/constellation:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/constellation-sociale
    depends_on: 
      - postgres
    command: [ "npm", "run", "db:setup" ] 